- hosts: localhost
  vars_files:
    - cred.yml
  tasks:
    - name: Running EC2 Role
      include_role:
        name: ec2

- hosts: namenode
  tasks:
    - name: Running Hadoop Master Role
      include_role:
        name: hadoop_master

- hosts: datanode
  tasks:
    - name: Running Hadoop Slave Role
      include_role:
        name: hadoop_slave

- hosts: clientnode
  tasks:
    - name: Running Hadoop Client Role
      include_role:
        name: hadoop_client